#!/bin/sh
set -eu

: "${FILE_STORAGE_PATH:?set FILE_STORAGE_PATH to the mounted private file root}"
: "${DATABASE_URL:?set DATABASE_URL for psql}"
: "${BACKEND_OFFLINE_CONFIRMED:?set BACKEND_OFFLINE_CONFIRMED=yes only after stopping all backend writers}"
[ "$BACKEND_OFFLINE_CONFIRMED" = yes ] || {
  echo "Refusing reconciliation without BACKEND_OFFLINE_CONFIRMED=yes" >&2
  exit 2
}

root=${FILE_STORAGE_PATH%/}
objects="$root/objects"
staging="$root/staging"
mkdir -p "$objects" "$staging"
raw=$(mktemp)
referenced=$(mktemp)
objects_list=$(mktemp)
trap 'rm -f "$raw" "$referenced" "$objects_list"' EXIT

# Do not put psql in a pipeline: POSIX set -e observes the query failure directly.
psql "$DATABASE_URL" --set ON_ERROR_STOP=1 --no-align --tuples-only \
  --command 'select storage_key from evidence_upload' > "$raw"
# Storage keys generated by the application are lowercase UUIDs. Any unexpected
# row aborts maintenance rather than making the reference set incomplete.
if grep -Ev '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' "$raw" | grep -q .; then
  echo "Refusing reconciliation: database returned an invalid storage key" >&2
  exit 3
fi
sort -u "$raw" > "$referenced"
# Portable across GNU and BusyBox/Alpine find (no -printf).
find "$objects" -mindepth 1 -maxdepth 1 -type f -exec basename {} \; | sort -u > "$objects_list"
comm -23 "$objects_list" "$referenced" | while IFS= read -r orphan; do
  [ -n "$orphan" ] && rm -- "$objects/$orphan"
done
# With the enforced offline precondition, staging parts cannot belong to active writers.
find "$staging" -mindepth 1 -maxdepth 1 -type f -name '*.part' -delete
# Worker directories are generated only with this prefix and are never committed.
# Do not follow symlinks or cross into an unexpected mount.
find -P "$staging" -mindepth 1 -maxdepth 1 -type d -name 'validate-*' -exec rm -rf -- {} +
