spring:
  http:
    converters:
      preferred-json-mapper: jackson2
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  session:
    jdbc:
      initialize-schema: never
  servlet:
    multipart:
      max-file-size: 10000001B
      max-request-size: 11MB
      resolve-lazily: true
server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: ${SECURE_COOKIES:true}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

licensing:
  file-storage-path: ${FILE_STORAGE_PATH:./data/private-files}
